Repository malmo-malmo/momo-server, pull requests merged in 2021-12, with the labels that each got.

#108 [BE] 응답 값에 생성 시간 추가
  server/src/main/java/com/momo/common/dto/EnumResponse.java
  server/src/main/java/com/momo/post/controller/dto/PostCardResponse.java
  server/src/main/java/com/momo/post/controller/dto/PostResponse.java
  server/src/main/java/com/momo/post/domain/repository/PostRepositoryCustomImpl.java
  server/src/main/java/com/momo/post/service/CommentService.java
  server/src/main/java/com/momo/post/service/PostService.java
  server/src/main/java/com/momo/schedule/controller/dto/GroupScheduleResponse.java
  server/src/test/java/com/momo/post/acceptance/step/PostAcceptanceStep.java
  server/src/test/java/com/momo/schedule/acceptance/step/ScheduleAcceptanceStep.java
Labels: 🔥백엔드, 수정

#109 [BE] 코드 리팩토링, 응답 값 변경
  server/src/main/java/com/momo/auth/domain/KakaoOAuthProvider.java
  server/src/main/java/com/momo/group/controller/dto/GroupResponse.java
  server/src/main/java/com/momo/group/domain/model/Groups.java
  server/src/main/java/com/momo/group/domain/repository/GroupRepositoryCustomImpl.java
  server/src/main/java/com/momo/group/service/ParticipantService.java
  server/src/main/java/com/momo/post/controller/dto/CommentResponse.java
  server/src/main/java/com/momo/post/controller/dto/PostResponse.java
  server/src/main/java/com/momo/post/service/PostService.java
  server/src/main/java/com/momo/schedule/controller/dto/GroupSchedulesResponse.java
  server/src/main/java/com/momo/schedule/service/ScheduleService.java
  server/src/main/java/com/momo/user/domain/model/User.java
  server/src/test/java/com/momo/fixture/UserFixture.java
  server/src/test/java/com/momo/group/acceptance/GroupAcceptanceTest.java
  server/src/test/java/com/momo/group/acceptance/step/GroupAcceptanceStep.java
  server/src/test/java/com/momo/post/acceptance/step/CommentAcceptanceStep.java
  server/src/test/java/com/momo/post/acceptance/step/PostAcceptanceStep.java
  server/src/test/java/com/momo/schedule/acceptance/ScheduleAcceptanceTest.java
  server/src/test/java/com/momo/schedule/acceptance/step/ScheduleAcceptanceStep.java
Labels: 리팩터링, 🔥백엔드, 수정

#116 [BE] 모임 탈퇴 API 추가
  server/src/main/java/com/momo/common/exception/ErrorCode.java
  server/src/main/java/com/momo/group/controller/GroupController.java
  server/src/main/java/com/momo/group/controller/ParticipantController.java
  server/src/main/java/com/momo/group/domain/model/Groups.java
  server/src/main/java/com/momo/group/domain/repository/ParticipantRepository.java
  server/src/main/java/com/momo/group/service/GroupService.java
  server/src/main/java/com/momo/group/service/ParticipantService.java
  server/src/main/java/com/momo/post/controller/CommentController.java
  server/src/main/java/com/momo/post/controller/PostController.java
  server/src/main/java/com/momo/post/service/CommentService.java
  server/src/main/java/com/momo/post/service/PostService.java
  server/src/main/java/com/momo/schedule/controller/ScheduleController.java
  server/src/main/java/com/momo/schedule/service/ScheduleService.java
  server/src/main/java/com/momo/user/controller/UniversityController.java
  server/src/main/java/com/momo/user/controller/UserController.java
  server/src/main/java/com/momo/user/service/UniversityService.java
  server/src/main/java/com/momo/user/service/UserService.java
  server/src/test/java/com/momo/common/acceptance/step/AcceptanceStep.java
  server/src/test/java/com/momo/group/acceptance/ParticipantAcceptanceTest.java
  server/src/test/java/com/momo/group/acceptance/step/ParticipantAcceptanceStep.java
Labels: 기능, 🔥백엔드

#120 [BE] 모임장 권한 양도 API, 내 정보 조회 API 추가
  server/src/main/java/com/momo/common/exception/ErrorCode.java
  server/src/main/java/com/momo/group/controller/GroupController.java
  server/src/main/java/com/momo/group/domain/model/Groups.java
  server/src/main/java/com/momo/group/service/GroupService.java
  server/src/main/java/com/momo/user/controller/UserController.java
  server/src/main/java/com/momo/user/controller/dto/UserResponse.java
  server/src/test/java/com/momo/common/acceptance/step/AcceptanceStep.java
  server/src/test/java/com/momo/group/acceptance/GroupAcceptanceTest.java
  server/src/test/java/com/momo/group/acceptance/step/GroupAcceptanceStep.java
  server/src/test/java/com/momo/user/acceptance/UserAcceptanceTest.java
  server/src/test/java/com/momo/user/acceptance/step/UserAcceptanceStep.java
Labels: 기능, 🔥백엔드

#123 [BE] Refresh 토큰 추가
  server/src/main/java/com/momo/auth/TokenProvider.java
  server/src/main/java/com/momo/auth/controller/OAuthController.java
  server/src/main/java/com/momo/auth/controller/dto/OAuthLoginResponse.java
  server/src/main/java/com/momo/auth/controller/dto/RefreshLoginRequest.java
  server/src/main/java/com/momo/auth/service/OAuthService.java
  server/src/main/java/com/momo/common/exception/ErrorCode.java
  server/src/main/java/com/momo/user/domain/model/User.java
  server/src/main/java/com/momo/user/domain/repository/UserRepository.java
  server/src/test/java/com/momo/auth/AuthAcceptanceTest.java
  server/src/test/java/com/momo/auth/step/AuthAcceptanceStep.java
  server/src/test/java/com/momo/common/acceptance/AcceptanceTest.java
  server/src/test/java/com/momo/common/acceptance/step/AcceptanceStep.java
Labels: 기능, 🔥백엔드

#131 [BE] 테스트 데이터 추가
  server/src/main/java/com/momo/DataLoader.java
  server/src/main/java/com/momo/MomoApplication.java
  server/src/main/resources/application.yml
  server/src/test/java/com/momo/MomoApplicationTests.java
Labels: 기능, 🔥백엔드

#133 [BE] 시/군/구 DB 구축, 조회 API 추가
  server/build.gradle
  server/src/main/java/com/momo/DistrictDataLoader.java
  server/src/main/java/com/momo/MockDataLoader.java
  server/src/main/java/com/momo/auth/domain/KakaoOAuthProvider.java
  server/src/main/java/com/momo/common/dto/EnumResponse.java
  server/src/main/java/com/momo/common/exception/ErrorCode.java
  server/src/main/java/com/momo/district/controller/DistrictController.java
  server/src/main/java/com/momo/district/controller/dto/DistrictResponse.java
  server/src/main/java/com/momo/district/domain/model/City.java
  server/src/main/java/com/momo/district/domain/model/District.java
  server/src/main/java/com/momo/district/domain/repository/DistrictRepository.java
  server/src/main/java/com/momo/user/domain/model/Location.java
  server/src/main/java/com/momo/user/domain/model/Role.java
  server/src/main/java/com/momo/utils/CookieUtils.java
  server/src/main/resources/db/district.xlsx
  server/src/test/java/com/momo/common/acceptance/AcceptanceTest.java
  server/src/test/java/com/momo/district/DistrictAcceptanceTest.java
  server/src/test/java/com/momo/district/step/DistrictAcceptanceStep.java
Labels: 기능, 리팩터링, 🔥백엔드

#150 [BE] 모임 상세 페이지 API Response 추가
  server/src/main/java/com/momo/group/controller/dto/GroupResponse.java
  server/src/main/java/com/momo/group/domain/repository/GroupRepositoryCustomImpl.java
  server/src/main/java/com/momo/user/controller/UserController.java
  server/src/main/java/com/momo/user/domain/model/User.java
  server/src/test/java/com/momo/fixture/UserFixture.java
  server/src/test/java/com/momo/group/acceptance/GroupAcceptanceTest.java
  server/src/test/java/com/momo/group/acceptance/step/GroupAcceptanceStep.java
Labels: 리팩터링, 🔥백엔드

#152 [BE] 모임 종료 API 추가
  server/src/main/java/com/momo/common/exception/ErrorCode.java
  server/src/main/java/com/momo/group/controller/GroupController.java
  server/src/main/java/com/momo/group/controller/dto/GroupResponse.java
  server/src/main/java/com/momo/group/controller/dto/ParticipantResponse.java
  server/src/main/java/com/momo/group/domain/model/Groups.java
  server/src/main/java/com/momo/group/domain/repository/ParticipantRepositoryCustomImpl.java
  server/src/main/java/com/momo/group/service/GroupService.java
  server/src/main/java/com/momo/post/service/PostService.java
  server/src/main/java/com/momo/schedule/service/ScheduleService.java
  server/src/main/java/com/momo/user/domain/model/User.java
  server/src/test/java/com/momo/auth/acceptance/AuthAcceptanceTest.java
  server/src/test/java/com/momo/common/acceptance/step/AcceptanceStep.java
  server/src/test/java/com/momo/group/acceptance/GroupAcceptanceTest.java
  server/src/test/java/com/momo/group/acceptance/ParticipantAcceptanceTest.java
  server/src/test/java/com/momo/group/acceptance/step/GroupAcceptanceStep.java
  server/src/test/java/com/momo/post/acceptance/PostAcceptanceTest.java
  server/src/test/java/com/momo/schedule/acceptance/ScheduleAcceptanceTest.java
Labels: 기능, 🔥백엔드

#173 [BE] ERD 설계
  server/module-core/src/main/java/com/momo/domain/group/domain/model/Participant.java
  server/module-core/src/main/resources/db/district.xlsx
  server/module-core/src/main/resources/db/table.sql
Labels: 기능, 🔥백엔드

#179 [BE] 배포를 위한 Dockerfile 작성
  server/Dockerfile
Labels: 🔥백엔드

#177 [BE] 슬라이스 테스트 템플릿 작성
  server/module-api/src/test/java/com/momo/IntegrationTest.java
  server/module-common/src/main/java/com/momo/TestProfile.java
  server/module-core/src/main/java/com/momo/domain/user/domain/model/User.java
  server/module-core/src/test/java/com/momo/RepositoryTest.java
  server/module-core/src/test/java/com/momo/ServiceTest.java
  server/module-core/src/test/java/com/momo/TestApplication.java
  server/module-core/src/test/java/com/momo/domain/group/domain/model/GroupsTest.java
  server/module-core/src/test/java/com/momo/domain/group/domain/repository/GroupRepositoryTest.java
  server/module-core/src/test/java/com/momo/domain/group/service/GroupServiceTest.java
Labels: 🔥백엔드

#183 [BE] jasypt 적용
  .gitignore
  server/build.gradle
  server/module-api/build.gradle
  server/module-api/src/main/java/com/momo/config/JasyptConfig.java
  server/module-api/src/main/resources/application-auth.yml
Labels: 기능, 🔥백엔드

#186 [BE] 개발 서버 배포를 위한 Dockerfile 수정
  server/Dockerfile
Labels: 우선순위 : 중, 🔥백엔드, 배포

#188 [BE] 개발 DB 설정 및 프로필 추가 작성
  server/module-api/build.gradle
  server/module-api/src/main/resources/application-dev.yml
  server/module-api/src/main/resources/application-local.yml
  server/module-api/src/main/resources/application.yml
Labels: 우선순위 : 하, 🔥백엔드, 배포

#190 [BE] logback 슬랙 연동
  server/module-api/build.gradle
  server/module-api/src/main/java/com/momo/MomoApplication.java
  server/module-api/src/main/java/com/momo/config/JasyptConfig.java
  server/module-api/src/main/resources/application-dev.yml
  server/module-api/src/main/resources/application-local.yml
  server/module-api/src/main/resources/logback/logback-dev.xml
  server/module-api/src/main/resources/logback/logback-local.xml
Labels: 우선순위 : 중, 🔥백엔드, 배포

#192 [BE] Spring Rest Docs 설정 및 예시 작성
  .gitignore
  server/module-api/build.gradle
  server/module-api/src/docs/asciidoc/group.adoc
  server/module-api/src/docs/asciidoc/index.adoc
  server/module-api/src/test/java/com/momo/RestDocsControllerTest.java
  server/module-api/src/test/java/com/momo/group/docs/GroupDocumentation.java
  server/module-api/src/test/java/com/momo/group/docs/GroupRestDocsTest.java
  server/module-api/src/test/resources/org/springframework/restdocs/templates/request-fields.snippet
Labels: 문서, 우선순위 : 중, 🔥백엔드

#194 [BE] Docker 파일 수정
  server/Dockerfile
Labels: 우선순위 : 하, 🔥백엔드, 배포

#200 [FE] 채팅 페이지 UI 작성
  client/momo/lib/app/routes/routes.dart
  client/momo/lib/app/ui/chat_list/chat_list_page.dart
  client/momo/lib/app/ui/chat_list/widget/chat_list_card.dart
  client/momo/lib/app/ui/chat_room/chat_room_page.dart
  client/momo/lib/app/ui/chat_room/widget/chat_bubble.dart
  client/momo/lib/app/ui/chat_room/widget/chat_message_row.dart
  client/momo/lib/app/ui/components/button/message_button.dart
  client/momo/lib/app/ui/home/home_page.dart
  client/momo/lib/app/ui/my_meet/my_meet_page.dart
  client/momo/lib/app/ui/search/search_page.dart
  client/momo/lib/app/util/theme.dart
Labels: 기능, 🦠프론트

#195 [BE] POJO 테스트 작성
  server/module-core/src/main/java/com/momo/domain/auth/domain/KakaoOAuthProvider.java
  server/module-core/src/main/java/com/momo/domain/group/domain/model/Participant.java
  server/module-core/src/main/java/com/momo/domain/schedule/domain/model/Attendance.java
  server/module-core/src/main/java/com/momo/domain/schedule/domain/model/Schedule.java
  server/module-core/src/main/java/com/momo/domain/schedule/service/AttendanceService.java
  server/module-core/src/main/java/com/momo/domain/user/domain/model/FavoriteCategories.java
  server/module-core/src/main/java/com/momo/domain/user/domain/model/User.java
  server/module-core/src/main/java/com/momo/domain/user/service/UserService.java
  server/module-core/src/test/java/com/momo/domain/group/GroupRepositoryTest.java
  server/module-core/src/test/java/com/momo/domain/group/GroupServiceTest.java
  server/module-core/src/test/java/com/momo/domain/group/GroupsTest.java
  server/module-core/src/test/java/com/momo/domain/group/ParticipantTest.java
  server/module-core/src/test/java/com/momo/domain/group/domain/model/GroupsTest.java
  server/module-core/src/test/java/com/momo/domain/post/CommentTest.java
  server/module-core/src/test/java/com/momo/domain/post/ImagesTest.java
  server/module-core/src/test/java/com/momo/domain/post/PostTest.java
  server/module-core/src/test/java/com/momo/domain/schedule/AttendanceTest.java
  server/module-core/src/test/java/com/momo/domain/schedule/ScheduleTest.java
  server/module-core/src/test/java/com/momo/domain/user/FavoriteCategoriesTest.java
  server/module-core/src/test/java/com/momo/domain/user/UserTest.java
  server/module-core/src/test/java/com/momo/domain/user/domain/model/UserTest.java
Labels: 🔥백엔드, 테스트

#203 [BE] REST Docs 문서 작성
  server/module-api/src/docs/asciidoc/comment.adoc
  server/module-api/src/docs/asciidoc/district.adoc
  server/module-api/src/docs/asciidoc/group.adoc
  server/module-api/src/docs/asciidoc/index.adoc
  server/module-api/src/docs/asciidoc/oauth.adoc
  server/module-api/src/docs/asciidoc/post.adoc
  server/module-api/src/docs/asciidoc/schedule.adoc
  server/module-api/src/docs/asciidoc/user.adoc
  server/module-api/src/main/java/com/momo/api/group/ParticipantController.java
  server/module-api/src/test/java/com/momo/auth/docs/OAuthDocumentation.java
  server/module-api/src/test/java/com/momo/auth/docs/OAuthRestDocsTest.java
  server/module-api/src/test/java/com/momo/district/docs/DistrictDocumentation.java
  server/module-api/src/test/java/com/momo/district/docs/DistrictRestDocsTest.java
  server/module-api/src/test/java/com/momo/group/docs/GroupDocumentation.java
  server/module-api/src/test/java/com/momo/group/docs/GroupRestDocsTest.java
  server/module-api/src/test/java/com/momo/group/docs/ParticipantDocumenttation.java
  server/module-api/src/test/java/com/momo/group/docs/ParticipantRestDocsTest.java
  server/module-api/src/test/java/com/momo/post/docs/CommentDocumentation.java
  server/module-api/src/test/java/com/momo/post/docs/CommentRestDocsTest.java
  server/module-api/src/test/java/com/momo/post/docs/PostDocumentation.java
  server/module-api/src/test/java/com/momo/post/docs/PostRestDocsTest.java
  server/module-api/src/test/java/com/momo/schedule/docs/AttendanceDocumentation.java
  server/module-api/src/test/java/com/momo/schedule/docs/AttendanceRestDocsTest.java
  server/module-api/src/test/java/com/momo/schedule/docs/ScheduleDocumentation.java
  server/module-api/src/test/java/com/momo/schedule/docs/ScheduleRestDocsTest.java
  server/module-api/src/test/java/com/momo/user/docs/UniversityDocumentation.java
  server/module-api/src/test/java/com/momo/user/docs/UniversityRestDocsTest.java
  server/module-api/src/test/java/com/momo/user/docs/UserDocumentation.java
  server/module-api/src/test/java/com/momo/user/docs/UserRestDocsTest.java
  server/module-api/src/test/resources/org/springframework/restdocs/templates/request-parameters.snippet
  server/module-core/src/main/java/com/momo/domain/common/domain/BaseEntity.java
  server/module-core/src/main/java/com/momo/domain/group/dto/GroupCardResponse.java
  server/module-core/src/main/java/com/momo/domain/group/dto/GroupResponse.java
  server/module-core/src/main/java/com/momo/domain/group/dto/ParticipantRequest.java
  server/module-core/src/main/java/com/momo/domain/post/domain/model/Comment.java
  server/module-core/src/main/java/com/momo/domain/post/dto/PostCardResponse.java
  server/module-core/src/main/java/com/momo/domain/schedule/dto/GroupScheduleResponse.java
Labels: 문서, 우선순위 : 중, 🔥백엔드
