Repository malmo-malmo/momo-server, pull requests merged in 2022-01, with the labels that each got.

#206 [BE] Service 테스트 작성
  server/module-api/src/main/java/com/momo/api/group/ParticipantController.java
  server/module-api/src/test/java/com/momo/group/acceptance/ParticipantAcceptanceTest.java
  server/module-core/src/main/java/com/momo/domain/common/exception/ErrorCode.java
  server/module-core/src/main/java/com/momo/domain/group/service/ParticipantService.java
  server/module-core/src/main/java/com/momo/domain/post/domain/model/Images.java
  server/module-core/src/main/java/com/momo/domain/post/dto/CommentCreateRequest.java
  server/module-core/src/main/java/com/momo/domain/post/dto/CommentsRequest.java
  server/module-core/src/main/java/com/momo/domain/schedule/dto/AttendanceCreateRequests.java
  server/module-core/src/main/java/com/momo/domain/schedule/dto/GroupSchedulesRequest.java
  server/module-core/src/main/java/com/momo/domain/schedule/service/ScheduleService.java
  server/module-core/src/test/java/com/momo/ServiceTest.java
  server/module-core/src/test/java/com/momo/domain/group/GroupServiceTest.java
  server/module-core/src/test/java/com/momo/domain/group/ParticipantServiceTest.java
  server/module-core/src/test/java/com/momo/domain/post/CommentServiceTest.java
  server/module-core/src/test/java/com/momo/domain/post/PostServiceTest.java
  server/module-core/src/test/java/com/momo/domain/schedule/AttendanceServiceTest.java
  server/module-core/src/test/java/com/momo/domain/schedule/ScheduleServiceTest.java
  server/module-core/src/test/java/com/momo/domain/user/UserServiceTest.java
Labels: 리팩터링, 🔥백엔드, 테스트

#209 [FE] 12/26일 수정사항
  client/momo/lib/app/provider/bottom_index_provider.dart
  client/momo/lib/app/provider/user/category_check_provder.dart
  client/momo/lib/app/provider/user/name_check_provider.dart
  client/momo/lib/app/provider/user/terms_check_provider.dart
  client/momo/lib/app/provider/user/university_controller_provider.dart
  client/momo/lib/app/provider/user/user_info__request_provider.dart
  client/momo/lib/app/ui/calendar/calendar_page.dart
  client/momo/lib/app/ui/components/dialog/university_result_dialog.dart
  client/momo/lib/app/ui/components/input_box/nickname_input_box.dart
  client/momo/lib/app/ui/components/input_box/university_input_box.dart
  client/momo/lib/app/ui/login/category_page.dart
  client/momo/lib/app/ui/login/info_page.dart
  client/momo/lib/app/ui/login/terms_page.dart
  client/momo/lib/app/ui/login/widget/input_box.dart
  client/momo/lib/app/ui/login/widget/terms_all_check_box.dart
  client/momo/lib/app/ui/login/widget/terms_row.dart
  client/momo/lib/app/ui/main_page.dart
Labels: 🦠프론트, 수정

#215 [BE] DTO 문자열 필드 enum 전환
  server/module-api/src/docs/asciidoc/user.adoc
  server/module-api/src/main/java/com/momo/api/user/UserController.java
  server/module-api/src/test/java/com/momo/fixture/GroupFixture.java
  server/module-api/src/test/java/com/momo/fixture/UserFixture.java
  server/module-api/src/test/java/com/momo/group/acceptance/GroupAcceptanceTest.java
  server/module-api/src/test/java/com/momo/group/acceptance/step/GroupAcceptanceStep.java
  server/module-api/src/test/java/com/momo/group/docs/GroupRestDocsTest.java
  server/module-api/src/test/java/com/momo/user/acceptance/UserAcceptanceTest.java
  server/module-api/src/test/java/com/momo/user/acceptance/step/UserAcceptanceStep.java
  server/module-api/src/test/java/com/momo/user/docs/UserDocumentation.java
  server/module-api/src/test/java/com/momo/user/docs/UserRestDocsTest.java
  server/module-core/src/main/java/com/momo/domain/common/dto/EnumResponse.java
  server/module-core/src/main/java/com/momo/domain/group/dto/GroupCreateRequest.java
  server/module-core/src/main/java/com/momo/domain/group/dto/GroupResponse.java
  server/module-core/src/main/java/com/momo/domain/group/dto/GroupSearchConditionRequest.java
  server/module-core/src/main/java/com/momo/domain/group/entity/Category.java
  server/module-core/src/main/java/com/momo/domain/group/entity/Groups.java
  server/module-core/src/main/java/com/momo/domain/group/repository/GroupRepositoryCustom.java
  server/module-core/src/main/java/com/momo/domain/group/repository/GroupRepositoryCustomImpl.java
  server/module-core/src/main/java/com/momo/domain/group/service/GroupService.java
  server/module-core/src/main/java/com/momo/domain/user/dto/FavoriteCategoriesUpdateRequest.java
  server/module-core/src/main/java/com/momo/domain/user/dto/UserResponse.java
  server/module-core/src/main/java/com/momo/domain/user/dto/UserUpdateRequest.java
  server/module-core/src/main/java/com/momo/domain/user/entity/User.java
  server/module-core/src/main/java/com/momo/domain/user/service/UserService.java
  server/module-core/src/main/java/com/momo/init/DistrictDataLoader.java
  server/module-core/src/main/java/com/momo/init/MockDataLoader.java
  server/module-core/src/test/java/com/momo/domain/group/repository/GroupRepositoryTest.java
  server/module-core/src/test/java/com/momo/domain/group/repository/ParticipantRepositoryTest.java
  server/module-core/src/test/java/com/momo/domain/group/service/GroupServiceTest.java
  server/module-core/src/test/java/com/momo/domain/post/repository/CommentRepositoryTest.java
  server/module-core/src/test/java/com/momo/domain/post/repository/ImageRepositoryTest.java
  server/module-core/src/test/java/com/momo/domain/post/repository/PostRepositoryTest.java
  server/module-core/src/test/java/com/momo/domain/schedule/repository/AttendanceRepositoryTest.java
  server/module-core/src/test/java/com/momo/domain/schedule/repository/ScheduleRepositoryTest.java
  server/module-core/src/test/java/com/momo/domain/user/repository/UserRepositoryTest.java
  server/module-core/src/test/java/com/momo/domain/user/service/UserServiceTest.java
Labels: 버그, 문서, 리팩터링, 🔥백엔드

#229 [BE] S3 이미지 업로드
  server/module-api/src/main/java/com/momo/api/group/GroupController.java
  server/module-api/src/main/java/com/momo/api/group/GroupsController.java
  server/module-api/src/main/java/com/momo/api/post/PostController.java
  server/module-api/src/main/java/com/momo/api/post/PostsController.java
  server/module-api/src/main/resources/application.yml
  server/module-api/src/main/resources/config/application-aws.yml
  server/module-api/src/test/java/com/momo/CommonFileUploadSupport.java
  server/module-api/src/test/java/com/momo/fixture/GroupFixture.java
  server/module-api/src/test/java/com/momo/fixture/PostFixture.java
  server/module-api/src/test/java/com/momo/group/acceptance/step/GroupAcceptanceStep.java
  server/module-api/src/test/java/com/momo/group/docs/GroupDocumentation.java
  server/module-api/src/test/java/com/momo/group/docs/GroupRestDocsTest.java
  server/module-api/src/test/java/com/momo/group/docs/GroupsRestDocsTest.java
  server/module-api/src/test/java/com/momo/post/acceptance/CommentAcceptanceTest.java
  server/module-api/src/test/java/com/momo/post/acceptance/PostAcceptanceTest.java
  server/module-api/src/test/java/com/momo/post/acceptance/step/PostAcceptanceStep.java
  server/module-api/src/test/java/com/momo/post/docs/PostDocumentation.java
  server/module-api/src/test/java/com/momo/post/docs/PostRestDocsTest.java
  server/module-api/src/test/java/com/momo/post/docs/PostsRestDocsTest.java
  server/module-api/src/test/java/com/momo/user/acceptance/step/UserAcceptanceStep.java
  server/module-api/src/test/resources/upload-test.png
  server/module-core/build.gradle
  server/module-core/src/main/java/com/momo/config/AwsS3Config.java
  server/module-core/src/main/java/com/momo/domain/aws/infra/S3Uploader.java
  server/module-core/src/main/java/com/momo/domain/aws/service/ImageUploadService.java
  server/module-core/src/main/java/com/momo/domain/aws/service/S3UploadService.java
  server/module-core/src/main/java/com/momo/domain/aws/util/GenerateUploadPathUtil.java
  server/module-core/src/main/java/com/momo/domain/group/dto/GroupCreateRequest.java
  server/module-core/src/main/java/com/momo/domain/group/entity/Group.java
  server/module-core/src/main/java/com/momo/domain/group/service/GroupService.java
  server/module-core/src/main/java/com/momo/domain/post/dto/PostCreateRequest.java
  server/module-core/src/main/java/com/momo/domain/post/service/PostService.java
  server/module-core/src/test/java/com/momo/domain/group/service/GroupServiceTest.java
  server/module-core/src/test/java/com/momo/domain/post/service/PostServiceTest.java
  server/module-core/src/test/resources/upload-test.png
Labels: 문서, 기능, 리팩터링, 🔥백엔드

#232 [BE] 참여 모임 API 추가, 지역 이름 변경
  server/module-api/src/docs/asciidoc/user.adoc
  server/module-api/src/main/java/com/momo/api/user/UserController.java
  server/module-api/src/test/java/com/momo/user/acceptance/UserAcceptanceTest.java
  server/module-api/src/test/java/com/momo/user/acceptance/step/UserAcceptanceStep.java
  server/module-api/src/test/java/com/momo/user/docs/UserDocumentation.java
  server/module-api/src/test/java/com/momo/user/docs/UserRestDocsTest.java
  server/module-core/src/main/java/com/momo/domain/district/entity/City.java
  server/module-core/src/main/java/com/momo/domain/group/repository/ParticipantRepository.java
  server/module-core/src/main/java/com/momo/domain/group/repository/ParticipantRepositoryCustom.java
  server/module-core/src/main/java/com/momo/domain/group/repository/ParticipantRepositoryCustomImpl.java
  server/module-core/src/main/java/com/momo/domain/user/dto/ParticipatingGroupCardResponse.java
  server/module-core/src/main/java/com/momo/domain/user/dto/ParticipatingGroupCountResponse.java
  server/module-core/src/main/java/com/momo/domain/user/service/GroupManagementService.java
  server/module-core/src/main/java/com/momo/init/DistrictDataLoader.java
  server/module-core/src/main/java/com/momo/init/MockDataLoader.java
  server/module-core/src/main/resources/db/district.xlsx
  server/module-core/src/test/java/com/momo/domain/group/repository/ParticipantRepositoryTest.java
  server/module-core/src/test/java/com/momo/domain/user/service/FavoriteGroupServiceTest.java
  server/module-core/src/test/java/com/momo/domain/user/service/GroupManagementServiceTest.java
Labels: 문서, 기능, 리팩터링, 🔥백엔드, 테스트

#234 [BE] 내 정보 수정 API 추가
  server/module-api/src/docs/asciidoc/user.adoc
  server/module-api/src/main/java/com/momo/api/user/UserController.java
  server/module-api/src/test/java/com/momo/CommonFileUploadSupport.java
  server/module-api/src/test/java/com/momo/auth/docs/OAuthRestDocsTest.java
  server/module-api/src/test/java/com/momo/group/docs/ParticipantRestDocsTest.java
  server/module-api/src/test/java/com/momo/post/docs/CommentRestDocsTest.java
  server/module-api/src/test/java/com/momo/schedule/docs/AttendanceRestDocsTest.java
  server/module-api/src/test/java/com/momo/schedule/docs/ScheduleRestDocsTest.java
  server/module-api/src/test/java/com/momo/user/acceptance/UserAcceptanceTest.java
  server/module-api/src/test/java/com/momo/user/acceptance/step/UserAcceptanceStep.java
  server/module-api/src/test/java/com/momo/user/docs/UserDocumentation.java
  server/module-api/src/test/java/com/momo/user/docs/UserRestDocsTest.java
  server/module-core/src/main/java/com/momo/domain/aws/service/S3UploadService.java
  server/module-core/src/main/java/com/momo/domain/common/dto/EnumResponse.java
  server/module-core/src/main/java/com/momo/domain/common/exception/ErrorCode.java
  server/module-core/src/main/java/com/momo/domain/user/dto/UserResponse.java
  server/module-core/src/main/java/com/momo/domain/user/dto/UserUpdateRequest.java
  server/module-core/src/main/java/com/momo/domain/user/entity/User.java
  server/module-core/src/main/java/com/momo/domain/user/service/UserService.java
  server/module-core/src/test/java/com/momo/domain/user/entity/UserTest.java
  server/module-core/src/test/java/com/momo/domain/user/service/UserServiceTest.java
Labels: 문서, 기능, 리팩터링, 🔥백엔드

#243 [BE] 게시글 수정, 삭제 및 댓글 삭제 API 구현. 그리고 기타 수정사항 반영
  server/module-api/src/docs/asciidoc/group.adoc
  server/module-api/src/docs/asciidoc/post.adoc
  server/module-api/src/docs/asciidoc/schedule.adoc
  server/module-api/src/main/java/com/momo/api/group/GroupController.java
  server/module-api/src/main/java/com/momo/api/post/CommentController.java
  server/module-api/src/main/java/com/momo/api/post/CommentsController.java
  server/module-api/src/main/java/com/momo/api/post/PostController.java
  server/module-api/src/main/java/com/momo/api/schedule/AttendanceController.java
  server/module-api/src/main/java/com/momo/api/schedule/ScheduleController.java
  server/module-api/src/test/java/com/momo/CommonFileUploadSupport.java
  server/module-api/src/test/java/com/momo/group/docs/GroupDocumentation.java
  server/module-api/src/test/java/com/momo/group/docs/GroupRestDocsTest.java
  server/module-api/src/test/java/com/momo/group/docs/GroupsRestDocsTest.java
  server/module-api/src/test/java/com/momo/group/docs/ParticipantRestDocsTest.java
  server/module-api/src/test/java/com/momo/post/acceptance/CommentAcceptanceTest.java
  server/module-api/src/test/java/com/momo/post/acceptance/PostAcceptanceTest.java
  server/module-api/src/test/java/com/momo/post/acceptance/step/CommentAcceptanceStep.java
  server/module-api/src/test/java/com/momo/post/acceptance/step/PostAcceptanceStep.java
  server/module-api/src/test/java/com/momo/post/docs/CommentRestDocsTest.java
  server/module-api/src/test/java/com/momo/post/docs/CommentsRestDocsTest.java
  server/module-api/src/test/java/com/momo/post/docs/PostDocumentation.java
  server/module-api/src/test/java/com/momo/post/docs/PostRestDocsTest.java
  server/module-api/src/test/java/com/momo/schedule/docs/AttendanceRestDocsTest.java
  server/module-api/src/test/java/com/momo/schedule/docs/ScheduleDocumentation.java
  server/module-api/src/test/java/com/momo/schedule/docs/ScheduleRestDocsTest.java
  server/module-core/src/main/java/com/momo/domain/common/exception/ErrorCode.java
  server/module-core/src/main/java/com/momo/domain/common/util/TimeFormatUtil.java
  server/module-core/src/main/java/com/momo/domain/group/service/GroupService.java
  server/module-core/src/main/java/com/momo/domain/group/service/ParticipantService.java
  server/module-core/src/main/java/com/momo/domain/group/service/impl/GroupServiceImpl.java
  server/module-core/src/main/java/com/momo/domain/group/service/impl/ParticipantServiceImpl.java
  server/module-core/src/main/java/com/momo/domain/post/dto/CommentResponse.java
  server/module-core/src/main/java/com/momo/domain/post/dto/PostResponse.java
  server/module-core/src/main/java/com/momo/domain/post/dto/PostUpdateRequest.java
  server/module-core/src/main/java/com/momo/domain/post/entity/Comment.java
  server/module-core/src/main/java/com/momo/domain/post/entity/Post.java
  server/module-core/src/main/java/com/momo/domain/post/repository/CommentRepository.java
  server/module-core/src/main/java/com/momo/domain/post/service/CommentService.java
  server/module-core/src/main/java/com/momo/domain/post/service/PostService.java
  server/module-core/src/main/java/com/momo/domain/post/service/impl/CommentServiceImpl.java
  server/module-core/src/main/java/com/momo/domain/post/service/impl/PostServiceImpl.java
  server/module-core/src/main/java/com/momo/domain/schedule/repository/ScheduleRepositoryCustom.java
  server/module-core/src/main/java/com/momo/domain/schedule/repository/ScheduleRepositoryCustomImpl.java
  server/module-core/src/main/java/com/momo/domain/schedule/service/AttendanceService.java
  server/module-core/src/main/java/com/momo/domain/schedule/service/ScheduleService.java
  server/module-core/src/main/java/com/momo/domain/schedule/service/impl/AttendanceServiceImpl.java
  server/module-core/src/main/java/com/momo/domain/schedule/service/impl/ScheduleServiceImpl.java
  server/module-core/src/test/java/com/momo/domain/common/TimeFormatUtilTest.java
  server/module-core/src/test/java/com/momo/domain/group/service/GroupServiceTest.java
  server/module-core/src/test/java/com/momo/domain/group/service/ParticipantServiceTest.java
  server/module-core/src/test/java/com/momo/domain/post/dto/CommentResponseTest.java
  server/module-core/src/test/java/com/momo/domain/post/dto/PostResponseTest.java
  server/module-core/src/test/java/com/momo/domain/post/service/CommentServiceTest.java
  server/module-core/src/test/java/com/momo/domain/post/service/PostServiceTest.java
  server/module-core/src/test/java/com/momo/domain/schedule/repository/ScheduleRepositoryTest.java
  server/module-core/src/test/java/com/momo/domain/schedule/service/AttendanceServiceTest.java
  server/module-core/src/test/java/com/momo/domain/schedule/service/ScheduleServiceTest.java
Labels: 우선순위 : 중, 기능, 🔥백엔드
