Repository malmo-malmo/momo-server, pull requests merged in 2022-02, with the labels that each got.

#267 [BE] 엔티티에서 특정 필드 임베디드 타입으로 분리
  server/module-api/src/test/java/com/momo/fixture/UserFixture.java
  server/module-api/src/test/java/com/momo/group/acceptance/GroupAcceptanceTest.java
  server/module-api/src/test/java/com/momo/group/docs/GroupRestDocsTest.java
  server/module-api/src/test/java/com/momo/user/acceptance/step/UserAcceptanceStep.java
  server/module-api/src/test/java/com/momo/user/docs/UserRestDocsTest.java
  server/module-core/src/main/java/com/momo/domain/auth/provider/KakaoOAuthProvider.java
  server/module-core/src/main/java/com/momo/domain/auth/service/OAuthService.java
  server/module-core/src/main/java/com/momo/domain/group/dto/GroupCreateRequest.java
  server/module-core/src/main/java/com/momo/domain/group/dto/GroupResponse.java
  server/module-core/src/main/java/com/momo/domain/group/entity/Group.java
  server/module-core/src/main/java/com/momo/domain/group/repository/GroupRepositoryCustomImpl.java
  server/module-core/src/main/java/com/momo/domain/group/service/impl/GroupServiceImpl.java
  server/module-core/src/main/java/com/momo/domain/user/dto/UserResponse.java
  server/module-core/src/main/java/com/momo/domain/user/dto/UserUpdateRequest.java
  server/module-core/src/main/java/com/momo/domain/user/dto/UserUpdateResponse.java
  server/module-core/src/main/java/com/momo/domain/user/entity/Location.java
  server/module-core/src/main/java/com/momo/domain/user/entity/Social.java
  server/module-core/src/main/java/com/momo/domain/user/entity/User.java
  server/module-core/src/main/java/com/momo/domain/user/repository/UserRepository.java
  server/module-core/src/main/java/com/momo/init/MockDataLoader.java
  server/module-core/src/test/java/com/momo/domain/favorite/repository/FavoriteGroupRepositoryTest.java
  server/module-core/src/test/java/com/momo/domain/group/entity/GroupListenerTest.java
  server/module-core/src/test/java/com/momo/domain/group/entity/GroupTest.java
  server/module-core/src/test/java/com/momo/domain/group/entity/ParticipantListenerTest.java
  server/module-core/src/test/java/com/momo/domain/group/repository/GroupRepositoryTest.java
  server/module-core/src/test/java/com/momo/domain/group/repository/ParticipantRepositoryTest.java
  server/module-core/src/test/java/com/momo/domain/group/service/GroupServiceTest.java
  server/module-core/src/test/java/com/momo/domain/post/repository/CommentRepositoryTest.java
  server/module-core/src/test/java/com/momo/domain/post/repository/ImageRepositoryTest.java
  server/module-core/src/test/java/com/momo/domain/post/repository/PostRepositoryTest.java
  server/module-core/src/test/java/com/momo/domain/schedule/repository/AttendanceRepositoryTest.java
  server/module-core/src/test/java/com/momo/domain/schedule/repository/ScheduleRepositoryTest.java
  server/module-core/src/test/java/com/momo/domain/user/entity/UserTest.java
  server/module-core/src/test/java/com/momo/domain/user/repository/UserRepositoryTest.java
Labels: 우선순위 : 하, 리팩터링, 🔥백엔드

#271 [BE] JaCoCo 적용
  server/build.gradle
  server/lombok.config
  server/momo-api/src/main/java/com/momo/api/auth/CurrentUser.java
  server/momo-api/src/main/java/com/momo/api/auth/CurrentUserArgumentResolver.java
  server/momo-api/src/main/java/com/momo/api/favorite/FavoriteController.java
  server/momo-api/src/main/java/com/momo/api/group/GroupController.java
  server/momo-api/src/main/java/com/momo/api/group/GroupsController.java
  server/momo-api/src/main/java/com/momo/api/group/ParticipantController.java
  server/momo-api/src/main/java/com/momo/api/management/ManagementController.java
  server/momo-api/src/main/java/com/momo/api/post/CommentController.java
  server/momo-api/src/main/java/com/momo/api/post/CommentsController.java
  server/momo-api/src/main/java/com/momo/api/post/PostController.java
  server/momo-api/src/main/java/com/momo/api/post/PostsController.java
  server/momo-api/src/main/java/com/momo/api/schedule/AttendanceController.java
  server/momo-api/src/main/java/com/momo/api/schedule/AttendancesController.java
  server/momo-api/src/main/java/com/momo/api/schedule/ScheduleController.java
  server/momo-api/src/main/java/com/momo/api/user/UserController.java
Labels: 기능, 🔥백엔드

#279 [BE] 로그인 관련 로직 수정
  server/momo-api/src/main/java/com/momo/api/auth/CurrentUserArgumentResolver.java
  server/momo-api/src/main/java/com/momo/api/auth/OAuthController.java
  server/momo-api/src/main/java/com/momo/common/AuthorizationExtractor.java
  server/momo-api/src/main/java/com/momo/config/InterceptorConfig.java
  server/momo-api/src/main/java/com/momo/config/WebMvcConfig.java
  server/momo-api/src/main/java/com/momo/interceptor/AuthorizationInterceptor.java
  server/momo-api/src/main/resources/config/application-auth.yml
  server/momo-api/src/test/java/com/momo/auth/acceptance/AuthAcceptanceTest.java
  server/momo-api/src/test/java/com/momo/auth/acceptance/step/AuthAcceptanceStep.java
  server/momo-api/src/test/java/com/momo/auth/docs/OAuthDocumentation.java
  server/momo-api/src/test/java/com/momo/auth/docs/OAuthRestDocsTest.java
  server/momo-api/src/test/java/com/momo/common/RestDocsControllerTest.java
  server/momo-api/src/test/java/com/momo/district/acceptance/DistrictAcceptanceTest.java
  server/momo-api/src/test/java/com/momo/district/acceptance/step/DistrictAcceptanceStep.java
  server/momo-api/src/test/java/com/momo/district/docs/DistrictRestDocsTest.java
  server/momo-api/src/test/java/com/momo/user/acceptance/UniversityAcceptanceTest.java
  server/momo-core/src/main/java/com/momo/domain/auth/dto/OAuthLoginRequest.java
  server/momo-core/src/main/java/com/momo/domain/auth/dto/RefreshLoginRequest.java
  server/momo-core/src/main/java/com/momo/domain/auth/provider/KakaoOAuthProvider.java
  server/momo-core/src/main/java/com/momo/domain/auth/provider/TokenProvider.java
  server/momo-core/src/main/java/com/momo/domain/auth/service/OAuthService.java
  server/momo-core/src/main/java/com/momo/domain/common/exception/ErrorCode.java
  server/momo-core/src/main/java/com/momo/domain/user/entity/Location.java
  server/momo-core/src/main/java/com/momo/domain/user/entity/LoginInfo.java
  server/momo-core/src/main/java/com/momo/domain/user/entity/User.java
  server/momo-core/src/main/java/com/momo/init/MockDataLoader.java
  server/momo-core/src/test/java/com/momo/domain/user/entity/LoginInfoTest.java
  server/momo-core/src/test/java/com/momo/domain/user/entity/UserTest.java
  server/momo-core/src/testFixtures/java/com/momo/UserFixture.java
  server/momo-core/src/testFixtures/java/com/momo/common/SocialFixture.java
Labels: 리팩터링, 🔥백엔드

#284 [BE] 요청사항, 버그 반영
  server/momo-api/src/main/java/com/momo/api/schedule/AttendanceController.java
  server/momo-api/src/test/java/com/momo/group/docs/ParticipantDocumenttation.java
  server/momo-api/src/test/java/com/momo/group/docs/ParticipantRestDocsTest.java
  server/momo-api/src/test/java/com/momo/schedule/acceptance/AttendanceAcceptanceTest.java
  server/momo-api/src/test/java/com/momo/schedule/acceptance/step/AttendanceAcceptanceStep.java
  server/momo-core/src/main/java/com/momo/domain/group/dto/ParticipantResponse.java
  server/momo-core/src/main/java/com/momo/domain/group/service/ParticipantService.java
  server/momo-core/src/main/java/com/momo/domain/group/service/impl/ParticipantServiceImpl.java
  server/momo-core/src/main/java/com/momo/domain/schedule/dto/AttendanceUpdateRequest.java
  server/momo-core/src/test/java/com/momo/domain/group/service/ParticipantServiceTest.java
  server/momo-core/src/testFixtures/java/com/momo/ParticipantFixture.java
Labels: 버그, 리팩터링, 🔥백엔드

#285 [BE] 다가오는 일정 API 추가
  server/momo-api/src/docs/asciidoc/schedule.adoc
  server/momo-api/src/main/java/com/momo/api/schedule/ScheduleController.java
  server/momo-api/src/test/java/com/momo/schedule/acceptance/ScheduleAcceptanceTest.java
  server/momo-api/src/test/java/com/momo/schedule/acceptance/step/ScheduleAcceptanceStep.java
  server/momo-api/src/test/java/com/momo/schedule/docs/ScheduleDocumentation.java
  server/momo-api/src/test/java/com/momo/schedule/docs/ScheduleRestDocsTest.java
  server/momo-core/src/main/java/com/momo/domain/schedule/dto/UpcomingScheduleResponse.java
  server/momo-core/src/main/java/com/momo/domain/schedule/entity/Schedule.java
  server/momo-core/src/main/java/com/momo/domain/schedule/repository/ScheduleRepository.java
  server/momo-core/src/main/java/com/momo/domain/schedule/service/ScheduleService.java
  server/momo-core/src/main/java/com/momo/domain/schedule/service/impl/ScheduleServiceImpl.java
  server/momo-core/src/test/java/com/momo/domain/schedule/repository/ScheduleRepositoryTest.java
  server/momo-core/src/test/java/com/momo/domain/schedule/service/ScheduleServiceTest.java
  server/momo-core/src/testFixtures/java/com/momo/ScheduleFixture.java
Labels: 기능, 🔥백엔드

#287 [BE] 소켓 모듈 초기 세팅
  server/momo-socket/build.gradle
  server/momo-socket/src/main/java/com/momo/MomoApplication.java
  server/momo-socket/src/main/java/com/momo/config/JasyptConfig.java
  server/momo-socket/src/main/java/com/momo/config/SocketConfig.java
  server/momo-socket/src/main/java/com/momo/config/SocketEventListener.java
  server/momo-socket/src/main/java/com/momo/config/TokenAuthInterceptor.java
  server/momo-socket/src/main/java/com/momo/config/model/SocketPrincipal.java
  server/momo-socket/src/main/resources/application-dev.yml
  server/momo-socket/src/main/resources/application-local.yml
  server/momo-socket/src/main/resources/application-test.yml
  server/momo-socket/src/main/resources/application.yml
  server/momo-socket/src/main/resources/config/application-auth.yml
  server/momo-socket/src/main/resources/config/application-aws.yml
  server/momo-socket/src/main/resources/config/application-env.yml
  server/momo-socket/src/main/resources/log4jdbc.log4j2.properties
  server/momo-socket/src/main/resources/logback/logback-dev.xml
  server/momo-socket/src/main/resources/logback/logback-local.xml
  server/momo-socket/src/test/java/com/momo/TestApplication.java
  server/momo-socket/src/test/java/com/momo/common/SocketTest.java
  server/settings.gradle
Labels: 우선순위 : 하, 기능, 🔥백엔드

#290 [BE] 슬랙 로깅 특정 에러 제외
  server/momo-api/src/main/java/com/momo/config/CustomThresholdFilter.java
  server/momo-api/src/main/resources/logback/logback-dev.xml
  server/momo-core/src/main/java/com/momo/domain/common/exception/ErrorCode.java
Labels: 우선순위 : 하, 리팩터링, 🔥백엔드

#292 [BE] API 로깅 + 슬랙 연동
  server/momo-api/build.gradle
  server/momo-api/src/main/java/com/momo/common/aop/LoggingAspect.java
  server/momo-api/src/main/java/com/momo/common/aop/PerformanceAspect.java
  server/momo-api/src/main/java/com/momo/config/CustomThresholdFilter.java
  server/momo-api/src/main/java/com/momo/filter/ReadableRequestWrapperFilter.java
  server/momo-api/src/main/java/com/momo/filter/SlackErrorLevelLogFilter.java
  server/momo-api/src/main/java/com/momo/filter/SlackInfoLevelLogFilter.java
  server/momo-api/src/main/java/com/momo/filter/SlackWarnLevelLogFilter.java
  server/momo-api/src/main/java/com/momo/interceptor/AuthorizationInterceptor.java
  server/momo-api/src/main/resources/application-dev.yml
  server/momo-api/src/main/resources/logback/logback-dev.xml
  server/momo-api/src/test/java/com/momo/common/RestDocsControllerTest.java
  server/momo-api/src/test/java/com/momo/common/acceptance/AcceptanceTest.java
  server/momo-common/src/main/java/com/momo/Profile.java
  server/momo-core/build.gradle
  server/momo-core/src/main/java/com/momo/init/DistrictDataLoader.java
  server/momo-core/src/main/java/com/momo/init/MockDataLoader.java
Labels: 기능, 🔥백엔드
